WebTasarimOdevi/WebTasarimOdevi/Controllers/GirisSayfasiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebTasarimOdevi.Models;

namespace WebTasarimOdevi.Controllers
{
    public class GirisSayfasiController : Controller
    {
        // GET: GirisSayfasi
        public ActionResult GirisS()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Kullanicilar(WebTasarimOdevi.Models.Kullanicilar kullanicilar)
        {
            using (ISKUREntities db = new ISKUREntities())
            {
                var userDetails = db.Kullanicilar.Where(x => x.KullaniciAdi == kullanicilar.KullaniciAdi && x.Şifre == kullanicilar.Şifre).FirstOrDefault();
                if (userDetails == null)
                {
                    kullanicilar.GirisEkraniHataMesaji = "Kullanici adi veya şifresi yanlış";

                    return View("GirisS", kullanicilar);
                }
                else
                {
                    Session["KullaniciID"] = userDetails.KullaniciID;
                    Session["KullaniciAdi"] = userDetails.KullaniciAdi;
                    return RedirectToAction("Anasayfa", "Sayfalar");
                }
            }
        }
        public ActionResult CikisYap()
        {
            int kullaniciId = (int)Session["KullaniciID"];
            Session.Abandon();
            return RedirectToAction("Anasayfa", "Sayfalar");
        }

      
    }
}

   

WebTasarimOdevi/WebTasarimOdevi/Views/GirisSayfasi/GirisS.cshtml
@model WebTasarimOdevi.Models.Kullanicilar
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <style>

        .butons {
            background-color: #751570;
            font-size: 16px;
            padding: 12px 28px;
            border-radius: 12px;
        }

        #login-div {
            background-color: #b584b4;
            position: absolute;
            left: 10%;
            right: 10%;
            top: 10%;
            border: 3px dashed #89158a;
            padding: 10px 10px;
        }

        .field-validation-error {
            color: red;
        }
    </style>

</head>
<body background="~/resimler/arkaplan2jpg.jpg">
    <div id="login-div">
        @using (Html.BeginForm("Kullanicilar", "GirisSayfasi", FormMethod.Post))
        {
            <table>
                <tr>
                    <td> </td>
                    <td style="text-decoration:underline">LÜtfen Bilgilerinizi giriniz</td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.KullaniciAdi)
                    </td>
                    <td>
                        @Html.EditorFor(model => Model.KullaniciAdi)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.ValidationMessageFor(model => model.KullaniciAdi)
                    </td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Şifre)</td>
                    <td>@Html.EditorFor(model => model.Şifre)</td>
                </tr>
                <tr>
                    <td>
                        @Html.ValidationMessageFor(model => model.Şifre)
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <label class="field-validation-error">@Html.DisplayFor(model => model.GirisEkraniHataMesaji)  </label>

                    </td>
                </tr>
                <tr>
                    <td>
                        <input class="butons" type="submit" name="name" value="GİRİŞ YAP" />


                    </td>
                </tr>
            </table>
        }
        <script src="~/Scripts/jquery-3.3.1.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    </div>
</body>
</html>